### ISSUE TITLE
bzz:list and swarm api are inconsistent

### ISSUE THREAD

**Issue by wanyvic** [MainframeHQ/erebos#115]
**version**
 @erebos/cli/0.10.0 darwin-x64 node-v10.15.1
swarm version 0.5.3-unstable
geth 1.9.6-stable
**code**
`wMacBook-Pro-282:testd wany$ erebos bzz:list da30bb001cc3a8f6537e81e92af3ccd67bbf3c0f51c8e256b75ba0c58ac21c61/master.m3u8`
✔ Retrieving list for da30bb001cc3a8f6537e81e92af3ccd67bbf3c0f51c8e256b75ba0c58ac21c61/master.m3u8
{}
`wMacBook-Pro-282:testd wany$ curl -s http://localhost:8500/bzz-list:/da30bb001cc3a8f6537e81e92af3ccd67bbf3c0f51c8e256b75ba0c58ac21c61/master.m3u8`
{"entries":[{"hash":"7fe9360fb8f3a9f328fccacc3fd03ad9890ba87dbb75c5dab070eb022732d53a","path":"master.m3u8","contentType":"application/vnd.apple.mpegurl","mode":420,"size":117,"mod_time":"2019-10-16T14:53:52+08:00"}]}
**summary**
upload a directory, when I try to get list of a files in this directory.erebos return a null,but swarm api not yet.
what's the reason?
thx a lot

**Comment by PaulLeCam** [comment]
Sorry I just realized it's not well documented on the website but the `bzz:list` command has a `path` flag you need to use for this, in your case: `erebos bzz:list da30bb001cc3a8f6537e81e92af3ccd67bbf3c0f51c8e256b75ba0c58ac21c61 --path=master.m3u8`

**Comment by wanyvic** [comment]
> Sorry I just realized it's not well documented on the website but the `bzz:list` command has a `path` flag you need to use for this, in your case: `erebos bzz:list da30bb001cc3a8f6537e81e92af3ccd67bbf3c0f51c8e256b75ba0c58ac21c61 --path=master.m3u8`

I got it,thanks
