### ISSUE TITLE
Support `bzz-feed-raw` scheme

### ISSUE THREAD

**Issue by PaulLeCam** [MainframeHQ/erebos#117]
Added in https://github.com/ethersphere/swarm/pull/1959

Might need to implement a way to compute the chunk address based on the [feed metadata](https://github.com/MainframeHQ/erebos/blob/e1c34a44052f0414c041f529fd8bbd8c2ddc5984/packages/api-bzz-base/src/types.ts#L53), as done in https://github.com/ethersphere/swarm/blob/3cf1468c0f975f6411e3644b380c598dfdd05d69/storage/feed/id.go#L42

Part of this change, the `FeedMetadata` interface could be renamed to `FeedID` to match Swarm's nomenclature.

**Comment by agazso** [comment]
Here is a javascript code that calculates the chunk address based on feed metadata:
https://github.com/agazso/swarm-dispochat/blob/ea2f6b4d7610012fc210877f26d2b9fab176a0d4/src/index.ts#L43

**Comment by PaulLeCam** [comment]
Nice, thanks!

**Comment by agazso** [comment]
I still have some issues using the `bzz-feed-raw` scheme, more specifically with the data it returns. I assume it returns the raw chunk data which includes the feed metadata, the actual stored data and then something else. For example if I store the string `swarm` it looks like this in hex:
```
00000000000000000000000000000000000000000000000000000000000000000000000000000000a62061e671a5aaf1e62197912064c3e0777ed0490300000000000000737761726ddd77aa6c612cff63e1f84d7f62fa5acaa6b1072ded24dae74815e26fc635a8583b7a8eb2b3cb02de5570b7d5463a57b903fa61601a1286ece6835ba772678d5201
```
From this the `a62061e671a5aaf1e62197912064c3e0777ed049` is the user address, `03` is the time and `737761726d` is the string `swarm`. Do you have any idea what the rest could mean or where is the chunk format is documented?

**Comment by agazso** [comment]
Ok, I found it in this PR:

https://github.com/ethersphere/swarm/commit/3cf1468c0f975f6411e3644b380c598dfdd05d69#diff-c9797bc2be092b92288d95af7b88dc69R338

The signature comes after the data. There are 68 bytes before the actual data starts and the signature is 65 bytes long.

**Comment by agazso** [comment]
See https://github.com/MainframeHQ/erebos/pull/127

**Comment by PaulLeCam** [comment]
Implemented in https://github.com/MainframeHQ/erebos/pull/127
