### ISSUE TITLE
Nested directory structures

### ISSUE THREAD

**Issue by AuHau** [MainframeHQ/erebos#118]
Not sure if it is problem of Erebos or actually Swarm, but it is not possible to add nested directory structure using `uploadDirectory` method.

For example
```js
const dir = {
      [`foo-${uploadContent}.txt`]: {
        data: `this is foo-${uploadContent}.txt`,
        contentType: 'plain/text',
      },
      [`bar-${uploadContent}.txt`]: {
        data: `this is bar-${uploadContent}.txt`,
        contentType: 'plain/text',
      },
      [`some/folder/bar-${uploadContent}.txt`]: { // <-------
        data: `this is bar-${uploadContent}.txt`,
        contentType: 'plain/text',
      },
    }
```

The file `some/folder/bar-${uploadContent}.txt` is not uploaded, or at least the `list()` does not return manifest that would either return the whole entry `some/folder/bar-${uploadContent}.txt` or at least `some` that would point to nested manifest.

Not sure what is the correct behavior or if it is a problem of Swarm, yet this is definitely unexpected behavior.

**Comment by PaulLeCam** [comment]
Could you open a PR with a test case please?
I just tried it out locally and it worked as expected, I could see the folder in the `common_prefixes` array of the manifest.

**Comment by AuHau** [comment]
Hmm maybe I am missing something from my not-complete understanding of Swarm, but I have created the #120 that for me locally fails.

**Comment by PaulLeCam** [comment]
Yes I think there's a misunderstanding of the expected behavior, the payload of the `bzz.uploadDirectory()` request and `bzz.list()` response are not the same, as you can see in the [DirectoryData](https://erebos.js.org/docs/api-bzz#directorydata) and [ListResult](https://erebos.js.org/docs/api-bzz#listresult) interfaces.

**Comment by AuHau** [comment]
Yeah, you are right. Thanks for the insight!
