### ISSUE TITLE
Not isomorphic API for Bzz

### ISSUE THREAD

**Issue by AuHau** [MainframeHQ/erebos#137]
Since the class for `bzz-browser` is exported as `BzzBrowser` and `bzz-node` is exported as `BzzNode` this prevents using the [`browser`](https://github.com/defunctzombie/package-browser-field-spec) field in `package.json` to create packages that easily work both in Node and browser as one is not a simple replacement of the other.

**Comment by PaulLeCam** [comment]
Sorry I don't think I understand the issue?
`@erebos/bzz` is isomorphic while `@erebos/bzz-browser` and `@erebos/bzz-node` are platform-specific, that's their purpose. They are not intended as being used as replacement for one-another.

**Comment by AuHau** [comment]
Sorry I forgot that you are not trying to actually make it isomorphic 😅 Pity in my opinion, but understandable.
