### ISSUE TITLE
Add support for request mode in `api-bzz-browser`

### ISSUE THREAD

**Issue by PaulLeCam** [MainframeHQ/erebos#51]
Adding the options to specify the [request mode](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode) in the browser APIs for Bzz would allow to clients to ignore server CORS settings when needed.

**Comment by f-dg** [comment]
Im supporting PaulLeCam or even better add an extra param in functions to have possibility adding custom headers for `fetch`
