### ISSUE TITLE
is this Compatible 'swarm 0.3.5'?

### ISSUE THREAD

**Issue by Nipol** [MainframeHQ/erebos#57]
geth
```sh
geth --syncmode light
```

swarm
```sh
swarm --bzzaccount 4fe9account --corsdomain '*' --maxpeers 100 --ens-api /Users/username/Library/Ethereum/geth.ipc –-ws --wsorigins '*'
```

```typescript
import { SwarmClient } from '@erebos/swarm-browser';

this.Client = new SwarmClient({ ws: 'ws://localhost:8546' });
console.log(this.Client);

const [publicKey, overlayAddress] = await Promise.all([
  this.Client.pss.getPublicKey(),
  this.Client.pss.baseAddr(),
]);

console.log(publicKey);
console.log(overlayAddress);
```

this isn't work. It does not work in any Browser.
However, if you run Onyx, the above code works.
What is the problem? Help me.

**Comment by PaulLeCam** [comment]
It's hard to say without more information, especially what error you're getting, but the [SwarmChat app](https://github.com/MainframeHQ/swarmchat/tree/master/dapp) works as expected for me running swarm 0.3.6 (build recently from source). I'm not aware of any specific issue related to 0.3.5.

**Comment by Nipol** [comment]
@PaulLeCam Oh. Sorry. The error history as

`WebSocket connection to 'ws://localhost:8546/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

When using this library, does not connect to Swarm from the Browser. :(
Can you tell what options you are running Swarm with?

**Comment by PaulLeCam** [comment]
Here are the flags I use locally (`$DIR` and `$KEY` are just defined in the bash script): `swarm --datadir $DIR --password $DIR/password --bzzport 8500 --httpaddr 0.0.0.0 --bzzaccount $KEY --ws --wsport 8546 --wsorigins "*" --corsdomain "*"`

Maybe you could try adding the `--httpaddr 0.0.0.0` flag, see if it makes any difference for Swarm?

**Comment by Nipol** [comment]
It also brings about the same effect. :( Have you ever reported a case like me?

**Comment by PaulLeCam** [comment]
Yes I've had this issue before due to bad configurations such as not setting the `--wsorigins` flag or running Swarm in a specific environment requiring additional config (docker).
Using a tool such as [wscat](https://www.npmjs.com/package/wscat) you can easily check if the problem comes from Erebos or the Swarm config depending on your ability to connect to the WebSocket with another client.

**Comment by Nipol** [comment]
@PaulLeCam I'm sooooo sorry, --ws flag had a fake hyphen. Your answer was very grateful.

**Comment by PaulLeCam** [comment]
Good to know you solved your issue!
