### ISSUE TITLE
uploadFromDirectory with defaultpath behaves differently than CLI upload

### ISSUE THREAD

**Issue by kyriediculous** [MainframeHQ/erebos#68]
From gitter with some additions:  

I ran into something weird using swarm CLI vs Erebos for uploading webapps to the swarm using the defaultPath option.

Uploaded with Erebos-JS: http://knuckle-swarm.designisdead.com/bzz:/e5cedbf7fc9a5dd92689d48b309ee2554e7c61591ecf319aa2b35bacb11cfb01/#/
Uploaded with Erebos- CLI : http://knuckle-swarm.designisdead.com/bzz:/818e3913b78905f3a237be58dd8a551d8baf0f77c163e14428587a842c15605f/#/

As you can see it seems like some css is missing (background is different) and some <link> tag for icon is partially displayed in the top corner. This only happens when using my Erebos-js script to upload, not when using Erebos-CLI or using a development server/local file system. I checked the built files and they are fine.

Erebos:CLI: `erebos bzz:upload .dist/pwa-mat --http-gateway http://knuckle-swarm.designisdead.com --default-path index.html`

Erebos-JS : 
```
const path = require('path')
const open = require('open')
const SwarmClient = require('@erebos/swarm').SwarmClient
const host = process.env.SWARM_HOST ||'http://knuckle-swarm.designisdead.com'
const clientType = process.env.CLIENT_TYPE || 'pwa-mat'

const bzz = new SwarmClient({bzz: host}).bzz
console.log('\x1b[33m%s\x1b[0m', `Bzz client started at ${host}`)

const directoryData = path.join(__dirname, 'dist', clientType)
console.log('\x1b[36m%s\x1b[0m', `Uploading ${clientType} from following path: ${directoryData}`)

const uploadOptions = {
  defaultPath: 'index.html'
}
console.log('\x1b[36m%s\x1b[0m', `Setting default path to resolve:  ${uploadOptions.defaultPath}`)

bzz.uploadDirectoryFrom(directoryData, uploadOptions).then(hash => open(`${host}/bzz:/${hash}`)).catch(e => console.log(e))

```

CLI renders fine: 
![afbeelding](https://user-images.githubusercontent.com/22256858/48156524-dd134200-e2cd-11e8-8a5b-50603d33c563.png)

Uploaded with the JS lib:
![afbeelding](https://user-images.githubusercontent.com/22256858/48156624-12b82b00-e2ce-11e8-9db4-b4e05b220e69.png)

version:
 "@erebos/swarm": "^0.4.0",

reproduction:
There is no access control on the nodes so you can just download the build files for now 
`erebos bzz:download 818e3913b78905f3a237be58dd8a551d8baf0f77c163e14428587a842c15605f --http-gateway http://knuckle-swarm.designisdead.com --path=./download-reproduction-content`

**Comment by PaulLeCam** [comment]
Hi @kyriediculous thanks for the details. I tried running it locally and I have the script correctly uploading the contents.
I think the issue might be that the `@erebos/swarm` package relies on multiple other packages that got patches recently, but if you're using a lockfile (`yarn.lock` with Yarn or `package-lock.json` with npm) the `@erebos/swarm` dependencies might still be the previous versions.
If you are indeed using a lockfile, could you please try to delete it and reinstall the packages please?

**Comment by kyriediculous** [comment]
That was indeed the problem. Thanks!
