### ISSUE TITLE
Replace custom Swarm docker image by official one

### ISSUE THREAD

**Issue by PaulLeCam** [MainframeHQ/erebos#72]
Better use https://github.com/ethersphere/swarm-docker directly if possible rather than having to maintain our own image.

**Comment by camronlevanger** [comment]
We should talk about this. I'm not sure we really want to tie ourselves to the Swarm team's timelines and automation.

**Comment by mosic** [comment]
I agree, we should discuss this together first.

**Comment by PaulLeCam** [comment]
I was thinking we would always use the specific tagged version of Swarm we try to support, I agree we should keep some control over what we use but it seems to duplicate the effort to have a custom Docker image in this repository doing pretty much the same thing.
Of course let's discuss this when we have the chance.

**Comment by mosic** [comment]
This is now in master, closing the issue.
