### ISSUE TITLE
Avoiding passing the privateKey around in the code

### ISSUE THREAD

**Issue by agazso** [MainframeHQ/erebos#80]
I have seen in the documentation that there are functions that get the `privateKey` as an argument for signing (for example https://erebos.js.org/docs/api-bzz#signfeeddigest).

It would be better from a security standpoint to not expose the `privateKey` to libraries that you are using, because there might be dependencies in the code that can potentially leak it by mistake or by malicious purposes.

It's possible to use for example a function that can be called when your data needs to be signed. You can pass that function instead of the `privateKey`, and when the underlying code needs to sign the data, it can simply call the function with the data as parameter.

It enables the library user to have more control over what happens when the app requires access to the privateKey, for example it can show a confirmation dialog (for example fingerprint check on mobile) or possibly can use an external wallet API .

What do you think?

**Comment by agazso** [comment]
That sounds good to me. Let me know if I can help with something.

**Comment by PaulLeCam** [comment]
I'll try to get started on these changes this week, as part of the other feeds-related changes I'm working on, maybe you could review the PR I'll open before merging the branch if you don't mind?
