### ISSUE TITLE
Progress on uploading file

### ISSUE THREAD

**Issue by IgorShadurin** [MainframeHQ/erebos#85]
Hi. Is it possible to add support for the progress in percents when uploading a file?
I'm using @erebos/swarm-browser in https://github.com/IgorShadurin/swarm-social-react. For the visual display of file uploading there is not enough progress callback function or something like that.

**Comment by PaulLeCam** [comment]
Hi, as far as I know the fetch API we're using doesn't support this yet, so a significant refactoring might be needed to support this kind of feature.
It is not currently a priority for us so not something we would be working on, but if you'd like to open a PR or discuss this further please don't hesitate.
