### ISSUE TITLE
yarn bootstrap changes source files

### ISSUE THREAD

**Issue by vujevits** [MainframeHQ/erebos#92]
reproduce (using node v10.14.2):
1. `git clone git@github.com:MainframeHQ/erebos.git`
2. `yarn install`
3. `yarn bootstrap`
4. `git status`

It seems that flow was changed to version 0.100 from 0.97, hence the slight change in the generated output, but the files were not committed, or gitignored, not sure what's the intended behavior.

**Comment by PaulLeCam** [comment]
Thanks for reporting this, I removed the `flow-typed` folder from source control, it should be created when running `yarn bootstrap`.

**Comment by vujevits** [comment]
works as expected 👍
