### ISSUE TITLE
gateway url has to have a closing slash

### ISSUE THREAD

**Issue by vujevits** [MainframeHQ/erebos#93]
### Description

If the gateway url does not contain a closing slash, the upload request will fail. 

### Example
`
const bzz = new BzzAPI({ url: `https://swarm-gateways.net` });
bzz.upload('some text');
`
Fails with network error
`
const bzz = new BzzAPI({ url: `https://swarm-gateways.net/` });
bzz.upload('some text');
`
Upload completes.

### Expected behavior

The documentation should be specific about it (at the moment not even the examples contain the slash), or both cases should be handled.

**Comment by PaulLeCam** [comment]
What package are you using please?
Both `@erebos/api-bzz-browser` and `@erebos/api-bzz-node` should behave as you describe already.

**Comment by vujevits** [comment]
I'm using @erebos/api-bzz-browser

**Comment by PaulLeCam** [comment]
What browser are you using please?
It seems its behavior with the `URL` interface is different from node, Chromium and Firefox that I tested.

**Comment by vujevits** [comment]
This was caused by my modifications, closing the issue.
