### ISSUE TITLE
createHex not found in @erebos/hex

### ISSUE THREAD

**Issue by nolash** [MainframeHQ/erebos#97]
In reference to: https://erebos.js.org/docs/hex - it may seem that docs are wrong or misleading;

Using code:

```
import { createHex } from '@erebos/hex';

console.log(createHex('foo'));
```

fails with:

```
$ ts-node test.ts 

/usr/lib/node_modules/ts-node/src/index.ts:245
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
test.ts:1:10 - error TS2305: Module '"./node_modules/@erebos/hex/types"' has no exported member 'createHex'.

1 import { createHex } from '@erebos/hex';

```

If I do this instead it works:

```
import { createHex } from '@erebos/swarm';

console.log(createHex('foo'));
```

**Comment by PaulLeCam** [comment]
In `@erebos/hex` the factory function is the default export, so it should be imported as
```js
import anyName from '@erebos/hex'
```
rather than being a named export such as
```js
import { Hex } from '@erebos/hex'
```

It's different in the `@erebos/swarm` package because it is re-exported using this specific name.
Sorry for the confusion, I think in a future release I'll switch to named exports everywhere.

**Comment by PaulLeCam** [comment]
Hey @nolash do you still have the issue please?
I changed it in v0.9 so `import { createHex } from '@erebos/hex'` should be the right way to import it now.

**Comment by nolash** [comment]
Now I can import with `import { createHex } from` but _not_ with `import createHex from` it's supposed to be like that?

Also, please excuse any potential ignorance regarding `npm` but I don't understand this:

```
$ npm install @erebos
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@erebos": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lash/.npm/_logs/2019-08-28T11_23_05_949Z-debug.log

$ npm install erebos
[...]
+ erebos@0.3.0
added 84 packages from 38 contributors and audited 239 packages in 5.264s
import createHex from '@erebos/hex';
found 0 vulnerabilities

$ npm install erebos/hex
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/erebos/hex.git
npm ERR! 
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lash/.npm/_logs/2019-08-28T11_26_25_100Z-debug.log

$ npm install @erebos/hex
[....]
+ @erebos/hex@0.9.0
added 1 package from 1 contributor and audited 1039 packages in 1.06s
found 0 vulnerabilities
```

in one case I have to use `@` the other not.

**Comment by PaulLeCam** [comment]
Yes only `import { createHex } from` should work with v0.9.

Regarding the npm installation errors, what happens is that originally all the APIs were published as a single package called `erebos`, but as new features got added we split the logic into multiple packages, such as `@erebos/hex`, `@erebos/api-pss`, etc.

The difference between `erebos` and `@erebos` is that `erebos` is the name of the package (now deprecated, you should use `@erebos/swarm-browser` or `@erebos/swarm-node` instead), while `@erebos` is the "organisation" name, basically a namespace so we can add any `@erebos/<whatever>` package to it.
Sorry for the confusion but basically you should never `npm install erebos`, it should always be `npm install @erebos/<package name>`, depending on the package you need.

**Comment by nolash** [comment]
I understand. If this is a self-evident thing in the world of `npm` then apologies for the noise. If not, then perhaps add a line about this in the documentation.
